name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Configure gcloud CLI
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker asia.gcr.io

    - name: Build and Push Docker image
      run: |
        docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-red-app .
        docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-red-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy node-red-app \
          --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-red-app \
          --region asia-northeast1 \
          --platform managed \
          --allow-unauthenticated

    - name: Notify via LINE (optional)
      if: success()
      run: |
        curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "to": "${{ secrets.LINE_USER_ID }}",
                "messages":[
                  {
                    "type":"flex",
                    "altText":"Node-REDデプロイ完了",
                    "contents":{ ...Flex Message JSON... }
                  }
                ]
              }'

