name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast2-docker.pkg.dev

      - name: Build and Push Docker image to Artifact Registry
        run: |
          docker buildx build --platform linux/amd64 \
            -t asia-northeast2-docker.pkg.dev/camera-line-webhook/camera-line-webhook/node-red-app \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy node-red-app \
            --image asia-northeast2-docker.pkg.dev/camera-line-webhook/camera-line-webhook/node-red-app \
            --region asia-northeast2 \
            --platform managed \
            --allow-unauthenticated

