name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast2-docker.pkg.dev

      - name: Build and Push Docker image to Artifact Registry
        run: |
          docker buildx build --platform linux/amd64 \
            -t asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/${{ secrets.GCP_SERVICE_NAME }} \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
            --image asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/${{ secrets.GCP_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-secrets LINE_CHANNEL_ACCESS_TOKEN=line-channel-token:latest,LINE_USER_ID=line-user-id:latest

      - name: Make Cloud Run publicly accessible
        run: |
          gcloud run services add-iam-policy-binding ${{ secrets.GCP_SERVICE_NAME }} \
            --region=${{ secrets.GCP_REGION }} \
            --member="allUsers" \
            --role="roles/run.invoker"

